DROP   DATABASE IF EXISTS Baifen;
CREATE DATABASE IF NOT EXISTS Baifen;

USE Baifen;

CREATE TABLE Player
(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL
);
